name: Main Workflow
on:
  push: # Triggered on a push event

jobs:
  reusable-1:
    uses: ./.github/workflows/reusable-1.yml
    with:
      input1: "Input for Reusable Workflow 1"

  reusable-2:
    needs: reusable-1
    uses: ./.github/workflows/reusable-2.yml
    with:
      result: ${{ needs.reusable-1.outputs.result }}

