name: Reusable Workflow 1
on:
  workflow_call:
    inputs:
      input1:
        required: true
        type: string
    outputs:
      result:
        description: "Result from Reusable Workflow 1"
        value: ${{ jobs.reusable1.outputs.result }}

jobs:
  reusable1:
    runs-on: ubuntu-latest
    outputs:
        result: ${{ steps.generate-output.outputs.result }}
    steps:
      - name: Generate Output
        id: generate-output
        run: | 
            echo "result=valuesss" >> $GITHUB_OUTPUT
            